version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-shift}
      POSTGRES_USER: ${POSTGRES_USER:-shift}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-shiftpass}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: ./backend
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-dev-secret}
      DEBUG: ${DEBUG:-True}
      POSTGRES_DB: ${POSTGRES_DB:-shift}
      POSTGRES_USER: ${POSTGRES_USER:-shift}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-shiftpass}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
